Slave
savvakek228/legendary-guacamole pull request #9
Opened 2020-05-25 18:52 UTC by savvakek228

2020-05-26 10:12 UTC, Toxin65 requested changes
Не соответствует ТЗ.

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.h
> +        explicit CellPos(int cellNum);
Такого конструктора нам не надо!

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.cpp
> +    if (getEmptyCells().empty())
У вас уже есть количества заполненных ячеек, используйте их.

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.cpp
> +        return FieldStatus::fsNoughtsWin;
Метод не предусматривает, если по ошибке состояние поля содержит две победы разных знаков.

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.cpp
> +    newField._field = _field;
А почему сразу не присвоить?
```suggestion
    PlayField newField = *this;
```

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.cpp
> +            countCells(CellStatus::csCross) > countCells(CellStatus::csNought)
Надо бы проверять строгость разности. Ассертнуть, чтоли.

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.cpp
> +           fieldStatus != FieldStatus::fsNormal);
Условие написано неверно.

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.cpp
> +            _field[2] == player && _field[4] == player && _field[6] == player;
magic values

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.cpp
> +            _field[i + 2 * multiplier] == player)
magic formulas

2020-05-26 10:12 UTC, Toxin65 commented on lab4/PlayField.h
> +    std::vector<CellStatus> _field = std::vector<CellStatus>(9, PlayField::CellStatus::csEmpty);
Зачем вектор то? И что такое 9?
Сделайте статический массив, ну или std::array если уж очень хочется.

2020-05-26 10:12 UTC, Toxin65 commented on lab4/TreeNode.h
> +    std::vector<std::reference_wrapper<TreeNode>> childNodes;
std::reference_wrapper
Надо хранить указатели, и потом по этим указателям потомков удалять в деструкторе.
Вангую у вас уже есть утечки памяти.

2020-05-26 10:12 UTC, Toxin65 commented on lab4/TreeNode.h
> +    PlayField currentField;
Не соответствует ТЗ.
 * Описать и использовать класс вершины TreeNode дерева решений, несущий в себе const экземпляр текущего состояния игрового поля PlayField, связи с предком и с потомками.

2020-05-26 15:35 UTC, savvakek228 commented on lab4/PlayField.cpp
> +            _field[2] == player && _field[4] == player && _field[6] == player;
почему они magic, если я их специально в переменной зафиксировал, и она встречается ровно один раз. Как вы предлагаете такое в constexpr написать или в define

2020-05-26 15:36 UTC, savvakek228 commented on lab4/TreeNode.h
> +    PlayField currentField;
Исправлю

2020-05-26 15:36 UTC, savvakek228 commented on lab4/TreeNode.h
> +    std::vector<std::reference_wrapper<TreeNode>> childNodes;
IDE предложила, мемчеком прошелся, утечек нет)

2020-05-26 15:44 UTC, savvakek228 commented on lab4/PlayField.h
> +    std::vector<CellStatus> _field = std::vector<CellStatus>(9, PlayField::CellStatus::csEmpty);
Ограничений на это в ТЗ не описано.

2020-05-26 17:49 UTC, savvakek228 commented on lab4/PlayField.h
> +        explicit CellPos(int cellNum);
Исправлю

2020-05-26 17:58 UTC, savvakek228 commented on lab4/PlayField.cpp
> +        return FieldStatus::fsNoughtsWin;
в ТЗ не написано, что такую ошибку учесть надо

2020-05-26 17:58 UTC, savvakek228 commented on lab4/PlayField.cpp
> +    newField._field = _field;
Согласен, переделаю

2020-05-26 18:00 UTC, savvakek228 commented on lab4/PlayField.cpp
> +            _field[i + 2 * multiplier] == player)
компилятор не поддерживает constexpr int в квадратных скобках

2020-05-26 18:12 UTC, savvakek228 commented on lab4/PlayField.cpp
> +            countCells(CellStatus::csCross) > countCells(CellStatus::csNought)
"надо бы", или "такая реализация не соответствует ТЗ"?

2020-05-28 18:24 UTC, Toxin65 commented on lab4/PlayField.cpp
> +        return FieldStatus::fsNoughtsWin;
В ТЗ не должно быть всё написано. Что вы меня тычите в ТЗ...
Я говорю как следует сделать с точки зрения создания надёжного ПО.

2020-05-28 18:27 UTC, Toxin65 commented on lab4/PlayField.cpp
> +            countCells(CellStatus::csCross) > countCells(CellStatus::csNought)
ТЗ не является строгим документом реализации.
Прекратите аппелировать к ТЗ постоянно.

2020-05-28 18:29 UTC, Toxin65 commented on lab4/PlayField.cpp
> +            _field[2] == player && _field[4] == player && _field[6] == player;
Потому что они ХЗ как родились в вашей голове.
Вы работаете кодером, вы в комманде не один. И даже если вы один -- следует писать так, чтобы после вашего увольнения ваш коллега мог поддерживать ваш код. А вы пишете неподдерживаемое "кю"...

2020-05-28 18:29 UTC, Toxin65 commented on lab4/PlayField.cpp
> +            _field[i + 2 * multiplier] == player)
Всё поддерживает, если правильно делать...

2020-05-28 18:30 UTC, Toxin65 commented on lab4/PlayField.h
> +    std::vector<CellStatus> _field = std::vector<CellStatus>(9, PlayField::CellStatus::csEmpty);
ТЗ -- это документация от заказчика.
Реализация плохая.

2020-05-28 18:31 UTC, Toxin65 commented on lab4/TreeNode.h
> +    std::vector<std::reference_wrapper<TreeNode>> childNodes;
Своей головой надо думать, а не IDE. Потому что утечки зависят от реализации программы. Не заставляйте меня показывать вам, что у вас есть утечки. Я это могу, но последствия будут таковыми, что работу я просто не приму...

2020-05-29 11:16 UTC, Toxin65 commented on lab4/PlayField.cpp
> +        return FieldStatus::fsNoughtsWin;
Поле допускает такое состояние? Значит надо учитывать.

2020-10-09 09:48 UTC, closed without merging